const IMAGES = {
    banner1: new URL("./banner1.jpg", import.meta.url).href,
    banner2: new URL("./banner2.jpg", import.meta.url).href,
    banner3: new URL("./banner3.jpg", import.meta.url).href,
    mainLogo: new URL("./mainLogo.svg", import.meta.url).href,
    prjCompleted: new URL("./completed.jpg", import.meta.url).href,
    prjOngoing: new URL("./ongoing.jpg", import.meta.url).href,
    prjUpcoming: new URL("./upcoming.jpg", import.meta.url).href,
    p5: new URL("./p5.jpg", import.meta.url).href,
    p1: new URL("./p1.jpg", import.meta.url).href,
    p2: new URL("./p2.jpg", import.meta.url).href,
    p3: new URL("./p3.jpg", import.meta.url).href,
    p4: new URL("./p4.jpg", import.meta.url).href,
    p6: new URL("./p6.jpg", import.meta.url).href,
    plane: new URL("./plane.png", import.meta.url).href,
    c: new URL("./c.jpg", import.meta.url).href,
    ekam: new URL("./ekam.jpeg", import.meta.url).href,
    onkar: new URL("./onkar.jpeg", import.meta.url).href,
    era: new URL("./ekam/era.jpg", import.meta.url).href,
    erb: new URL("./ekam/erb.jpg", import.meta.url).href,
    erc: new URL("./ekam/erc.jpg", import.meta.url).href,
    erd: new URL("./ekam/erd.jpg", import.meta.url).href,
    ere: new URL("./ekam/ere.jpg", import.meta.url).href,
    ora: new URL("./onkar/ora.jpg", import.meta.url).href,
    orb: new URL("./onkar/orb.jpg", import.meta.url).href,
    orc: new URL("./onkar/orc.jpg", import.meta.url).href,
    ord: new URL("./onkar/ord.jpg", import.meta.url).href,
};

export default IMAGES;
